# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [57]:
import numpy as np
import pandas as pd 
import io
import requests

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
s = requests.get(url).content
users = pd.read_table(io.StringIO(s.decode('utf-8')),sep='|')
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. Discover what is the mean age per occupation

In [6]:
for i in users:
    print('The occupation ' +users['occupation'] +" " +str(users['age'].mean()) + ' is  the mean age for every occupation ')

0      The occupation technician 34.05196182396607 is...
1      The occupation other 34.05196182396607 is  the...
2      The occupation writer 34.05196182396607 is  th...
3      The occupation technician 34.05196182396607 is...
4      The occupation other 34.05196182396607 is  the...
                             ...
938    The occupation student 34.05196182396607 is  t...
939    The occupation administrator 34.05196182396607...
940    The occupation student 34.05196182396607 is  t...
941    The occupation librarian 34.05196182396607 is ...
942    The occupation student 34.05196182396607 is  t...
Name: occupation, Length: 943, dtype: object
0      The occupation technician 34.05196182396607 is...
1      The occupation other 34.05196182396607 is  the...
2      The occupation writer 34.05196182396607 is  th...
3      The occupation technician 34.05196182396607 is...
4      The occupation other 34.05196182396607 is  the...
                             ...
938    The occupation student 34.05196182396607 is  t...
939    The occupation administrator 34.05196182396607...
940    The occupation student 34.05196182396607 is  t...
941    The occupation librarian 34.05196182396607 is ...
942    The occupation student 34.05196182396607 is  t...
Name: occupation, Length: 943, dtype: object
0      The occupation technician 34.05196182396607 is...
1      The occupation other 34.05196182396607 is  the...
2      The occupation writer 34.05196182396607 is  th...
3      The occupation technician 34.05196182396607 is...
4      The occupation other 34.05196182396607 is  the...
                             ...
938    The occupation student 34.05196182396607 is  t...
939    The occupation administrator 34.05196182396607...
940    The occupation student 34.05196182396607 is  t...
941    The occupation librarian 34.05196182396607 is ...
942    The occupation student 34.05196182396607 is  t...
Name: occupation, Length: 943, dtype: object
0      The occupation technician 34.05196182396607 is...
1      The occupation other 34.05196182396607 is  the...
2      The occupation writer 34.05196182396607 is  th...
3      The occupation technician 34.05196182396607 is...
4      The occupation other 34.05196182396607 is  the...
                             ...
938    The occupation student 34.05196182396607 is  t...
939    The occupation administrator 34.05196182396607...
940    The occupation student 34.05196182396607 is  t...
941    The occupation librarian 34.05196182396607 is ...
942    The occupation student 34.05196182396607 is  t...
Name: occupation, Length: 943, dtype: object
0      The occupation technician 34.05196182396607 is...
1      The occupation other 34.05196182396607 is  the...
2      The occupation writer 34.05196182396607 is  th...
3      The occupation technician 34.05196182396607 is...
4      The occupation other 34.05196182396607 is  the...
                             ...
938    The occupation student 34.05196182396607 is  t...
939    The occupation administrator 34.05196182396607...
940    The occupation student 34.05196182396607 is  t...
941    The occupation librarian 34.05196182396607 is ...
942    The occupation student 34.05196182396607 is  t...
Name: occupation, Length: 943, dtype: object

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [25]:
for i in users.gender:
    print(users.occupation +" " +str(users.gender.value_counts()))

0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...
942    student M    670\nF    273\nName: gender, dtyp...
Name: occupation, Length: 943, dtype: object
0      technician M    670\nF    273\nName: gender, d...
1      other M    670\nF    273\nName: gender, dtype:...
2      writer M    670\nF    273\nName: gender, dtype...
3      technician M    670\nF    273\nName: gender, d...
4      other M    670\nF    273\nName: gender, dtype:...
                             ...
938    student M    670\nF    273\nName: gender, dtyp...
939    administrator M    670\nF    273\nName: gender...
940    student M    670\nF    273\nName: gender, dtyp...
941    librarian M    670\nF    273\nName: gender, dt...

In [28]:
x=users.gender.value_counts()
x.sort_values()

F    273
M    670
Name: gender, dtype: int64

In [30]:
g = users.groupby("gender")
g

In [35]:
for gender, data in g:
    print("occupation:",g.occupation)
    print("gender:",gender)
    
    print("data:",data)
    print("\n")

occupation: <pandas.core.groupby.generic.SeriesGroupBy object at 0x000002C74460FDC0>
gender: F
data:      user_id  age gender  occupation zip_code
1          2   53      F       other    94043
4          5   33      F       other    15213
10        11   39      F       other    30329
11        12   28      F       other    06405
14        15   49      F    educator    97301
..       ...  ...    ...         ...      ...
924      925   18      F    salesman    49036
929      930   28      F   scientist    07310
937      938   38      F  technician    55038
938      939   26      F     student    33319
941      942   48      F   librarian    78209

[273 rows x 5 columns]


occupation: <pandas.core.groupby.generic.SeriesGroupBy object at 0x000002C74460F3A0>
gender: M
data:      user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
2          3   23      M         writer    32067
3          4   24      M     technician    43537
5          6   42      M      executive    98101
6          7   57      M  administrator    91344
..       ...  ...    ...            ...      ...
935      936   24      M          other    32789
936      937   48      M       educator    98072
939      940   32      M  administrator    02215
940      941   20      M        student    97229
942      943   22      M        student    77841

[670 rows x 5 columns]

In [37]:
g.max()

        user_id  age occupation zip_code
gender
F           942   70     writer    V5A2B
M           943   73     writer    Y1A6B

### Step 6. For each occupation, calculate the minimum and maximum ages

In [26]:
for i in users:
    print("the occupation "+ users.occupation+ "the max age is ("+str(users.occupation.max())+") and the min is ( "+str(users.occupation.min())+" )")

0      the occupation technicianthe max age is (write...
1      the occupation otherthe max age is (writer) an...
2      the occupation writerthe max age is (writer) a...
3      the occupation technicianthe max age is (write...
4      the occupation otherthe max age is (writer) an...
                             ...
938    the occupation studentthe max age is (writer) ...
939    the occupation administratorthe max age is (wr...
940    the occupation studentthe max age is (writer) ...
941    the occupation librarianthe max age is (writer...
942    the occupation studentthe max age is (writer) ...
Name: occupation, Length: 943, dtype: object
0      the occupation technicianthe max age is (write...
1      the occupation otherthe max age is (writer) an...
2      the occupation writerthe max age is (writer) a...
3      the occupation technicianthe max age is (write...
4      the occupation otherthe max age is (writer) an...
                             ...
938    the occupation studentthe max age is (writer) ...
939    the occupation administratorthe max age is (wr...
940    the occupation studentthe max age is (writer) ...
941    the occupation librarianthe max age is (writer...
942    the occupation studentthe max age is (writer) ...
Name: occupation, Length: 943, dtype: object
0      the occupation technicianthe max age is (write...
1      the occupation otherthe max age is (writer) an...
2      the occupation writerthe max age is (writer) a...
3      the occupation technicianthe max age is (write...
4      the occupation otherthe max age is (writer) an...
                             ...
938    the occupation studentthe max age is (writer) ...
939    the occupation administratorthe max age is (wr...
940    the occupation studentthe max age is (writer) ...
941    the occupation librarianthe max age is (writer...
942    the occupation studentthe max age is (writer) ...
Name: occupation, Length: 943, dtype: object
0      the occupation technicianthe max age is (write...
1      the occupation otherthe max age is (writer) an...
2      the occupation writerthe max age is (writer) a...
3      the occupation technicianthe max age is (write...
4      the occupation otherthe max age is (writer) an...
                             ...
938    the occupation studentthe max age is (writer) ...
939    the occupation administratorthe max age is (wr...
940    the occupation studentthe max age is (writer) ...
941    the occupation librarianthe max age is (writer...
942    the occupation studentthe max age is (writer) ...
Name: occupation, Length: 943, dtype: object
0      the occupation technicianthe max age is (write...
1      the occupation otherthe max age is (writer) an...
2      the occupation writerthe max age is (writer) a...
3      the occupation technicianthe max age is (write...
4      the occupation otherthe max age is (writer) an...
                             ...
938    the occupation studentthe max age is (writer) ...
939    the occupation administratorthe max age is (wr...
940    the occupation studentthe max age is (writer) ...
941    the occupation librarianthe max age is (writer...
942    the occupation studentthe max age is (writer) ...
Name: occupation, Length: 943, dtype: object

### Step 7. For each combination of occupation and gender, calculate the mean age

In [47]:
x=users.groupby("gender")
x

In [50]:
y=x.get_group("M")
y

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
2          3   23      M         writer    32067
3          4   24      M     technician    43537
5          6   42      M      executive    98101
6          7   57      M  administrator    91344
..       ...  ...    ...            ...      ...
935      936   24      M          other    32789
936      937   48      M       educator    98072
939      940   32      M  administrator    02215
940      941   20      M        student    97229
942      943   22      M        student    77841

[670 rows x 5 columns]

In [51]:
t=x.get_group("F")
t

     user_id  age gender  occupation zip_code
1          2   53      F       other    94043
4          5   33      F       other    15213
10        11   39      F       other    30329
11        12   28      F       other    06405
14        15   49      F    educator    97301
..       ...  ...    ...         ...      ...
924      925   18      F    salesman    49036
929      930   28      F   scientist    07310
937      938   38      F  technician    55038
938      939   26      F     student    33319
941      942   48      F   librarian    78209

[273 rows x 5 columns]

In [56]:
users.pivot_table(index="occupation",columns="gender",values="age", aggfunc=np.average)

gender                 F          M
occupation
administrator  40.638889  37.162791
artist         30.307692  32.333333
doctor               NaN  43.571429
educator       39.115385  43.101449
engineer       29.500000  36.600000
entertainment  31.000000  29.000000
executive      44.000000  38.172414
healthcare     39.818182  45.400000
homemaker      34.166667  23.000000
lawyer         39.500000  36.200000
librarian      40.000000  40.000000
marketing      37.200000  37.875000
none           36.500000  18.600000
other          35.472222  34.028986
programmer     32.166667  33.216667
retired        70.000000  62.538462
salesman       27.000000  38.555556
scientist      28.333333  36.321429
student        20.750000  22.669118
technician     38.000000  32.961538
writer         37.631579  35.346154

### Step 8.  For each occupation present the percentage of women and men

In [61]:
users.gender.value_counts()

M    670
F    273
Name: gender, dtype: int64

In [62]:
users['gender'].count

<bound method Series.count of 0      M
1      F
2      M
3      M
4      F
      ..
938    F
939    M
940    M
941    F
942    M
Name: gender, Length: 943, dtype: object>

In [64]:
women=(670/943)*100
women

71.04984093319194

In [65]:
men=(273/943)*100
men

28.950159066808055

In [97]:
users.pivot_table(index="gender",columns="occupation", margins=True, aggfunc=np.average)

C:\Users\hp\AppData\Local\Temp\ipykernel_6692\770163249.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the function.
  users.pivot_table(index="gender",columns="occupation", margins=True, aggfunc=np.average)
C:\Users\hp\AppData\Local\Temp\ipykernel_6692\770163249.py:1: FutureWarning: ['zip_code'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  users.pivot_table(index="gender",columns="occupation", margins=True, aggfunc=np.average)
C:\Users\hp\AppData\Local\Temp\ipykernel_6692\770163249.py:1: FutureWarning: ['zip_code'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  users.pivot_table(index="gender",columns="occupation", margins=True, aggfunc=np.average)

                     age                                             \
occupation administrator     artist     doctor   educator  engineer
gender
F              40.638889  30.307692        NaN  39.115385  29.50000
M              37.162791  32.333333  43.571429  43.101449  36.60000
All            38.746835  31.392857  43.571429  42.010526  36.38806

                                                                  ...  \
occupation entertainment  executive healthcare  homemaker lawyer  ...
gender                                                            ...
F              31.000000  44.000000  39.818182  34.166667  39.50  ...
M              29.000000  38.172414  45.400000  23.000000  36.20  ...
All            29.222222  38.718750  41.562500  32.571429  36.75  ...

               user_id                                                  \
occupation        none       other  programmer     retired    salesman
gender
F           521.750000  474.666667  411.166667  860.000000  637.666667
M           246.200000  578.246377  437.966667  489.230769  447.333333
All         368.666667  542.733333  435.530303  515.714286  494.916667


occupation   scientist     student  technician      writer         All
gender
F           611.666667  497.533333  938.000000  536.052632  481.406593
M           449.428571  479.404412  480.692308  466.230769  468.167164
All         465.129032  484.954082  497.629630  495.711111  472.000000

[3 rows x 44 columns]